// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [
    // --- ОБЩЕЕ ---
    {
      type: 'category',
      label: 'Общее',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'general' }],
    },

    // --- ЧТО НОВОГО ---
    {
      type: 'category',
      label: 'Что нового',
      link: {
        type: 'doc',
        id: 'whatsnew/whatsnew', // путь к файлу docs/technical/requirements.md
      },
      items: [],
    },

    // --- ИНТЕРФЕЙС ---
    {
      type: 'category',
      label: 'Интерфейс',
      link: {
        type: 'doc',
        id: 'interface/index', // путь к файлу docs/technical/requirements.md
      },
      items: [],
    },

// --- ВЫКРОЙКИ ---
{
  type: 'category',
  label: 'Выкройки',
  link: { type: 'generated-index' },
  items: [
    // Intro.md
    {
      type: 'doc',
      id: 'patterns/intro', // путь: /docs/patterns/intro.md
      label: 'Общее',
    },

    // Действия с выкройками
    {
      type: 'category',
      label: 'Действия с выкройками',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'patterns/actions' }],
    },

    // Шаблоны отдельных деталей
    {
      type: 'category',
      label: 'Шаблоны отдельных деталей',
      link: { type: 'generated-index' },
      items: [
        { type: 'autogenerated', dirName: 'patterns/pieces/common' },
        { type: 'autogenerated', dirName: 'patterns/pieces/rectangle' },
        { type: 'autogenerated', dirName: 'patterns/pieces/hat' },
        { type: 'autogenerated', dirName: 'patterns/pieces/raglan-yoke' },
        { type: 'autogenerated', dirName: 'patterns/pieces/front-dart' },
        { type: 'autogenerated', dirName: 'patterns/pieces/set-in-sleeve' },
      ],
    },

    // Шаблоны целых вещей
    {
      type: 'category',
      label: 'Шаблоны целых вещей',
      link: { type: 'generated-index' },
      items: [
        { type: 'autogenerated', dirName: 'patterns/full/common' },
        { type: 'autogenerated', dirName: 'patterns/full/scarves-hats' },
        { type: 'autogenerated', dirName: 'patterns/full/sweaters' },
      ],
    },
  ],
},

    // --- ВЯЗАНИЕ ---
    {
      type: 'category',
      label: 'Вязание',
      link: { type: 'generated-index' },
      items: [
        // Intro.md
        {
          type: 'doc',
          id: 'knitting/intro', // путь: /docs/knitting/intro.md
          label: 'Общее',
        },
        // Общее
        {
          type: 'category',
          label: 'Общее',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'knitting/general' }],
        },
        // Рисование
        {
          type: 'category',
          label: 'Редактирование петель по одной (рисование)',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'knitting/draw' }],
        },
        // Выделение
        {
          type: 'category',
          label: 'Выделение петель',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'knitting/select' }],
        },
        // Редактирование блока
        {
          type: 'category',
          label: 'Редактирование выделенного блока петель',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'knitting/block-edit' }],
        },
        // Направление
        {
          type: 'category',
          label: 'Направление вязания',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'knitting/direction' }],
        },
        // Пряжа
        {
          type: 'category',
          label: 'Пряжа',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'knitting/yarn' }],
        },
        // Плотность
        {
          type: 'category',
          label: 'Плотность',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'knitting/tension' }],
        },
        // Узоры из петель
        {
          type: 'category',
          label: 'Узоры из петель',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'knitting/stitch-patterns' }],
        },
        // Цветные узоры
        {
          type: 'category',
          label: 'Цветные узоры',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'knitting/colorwork' }],
        },
        // Библиотека узоров
        {
          type: 'category',
          label: 'Библиотека узоров',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'knitting/library' }],
        },
        // Генератор узоров
        {
          type: 'category',
          label: 'Генератор узоров',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'knitting/generator' }],
        },
      ],
    },

    // --- СОХРАНЕНИЕ И ЭКСПОРТ ---
    {
      type: 'category',
      label: 'Сохранение и экспорт',
      link: {
        type: 'doc',
        id: 'export/export', // путь к файлу docs/technical/requirements.md
      },
      items: [],
    },

    // --- ТЕХНИЧЕСКИЕ ТРЕБОВАНИЯ ---
    {
      type: 'category',
      label: 'Технические требования',
      link: {
        type: 'doc',
        id: 'technical/requirements', // путь к файлу docs/technical/requirements.md
      },
      items: [],
    },
  ],
};

export default sidebars;
